credentials:
  usernames:
    alexander:
      email: alex@example.com
      name: Alexander Tiopan
      password: "$2b$12$bPaGNCYB/YA/yxcdwLhgv.HYZHn7dWe8e8NT7Nvit93niOBlrXrZy"
    sabrina:
      email: sabrina@example.com
      name: Sabrina
      password: "$2b$12$Z12UqNpGvcjYFsd8FrR3oeNAIpP8IbP3/iYtDu.VKLWGF8mA7zxQm"

cookie:
  expiry_days: 3
  key: supersecurekey
  name: datapulse_login

preauthorized:
  emails:
    - alex@example.com
    - sabrina@example.com